// Tom's batch-upload filing scenario — Project Aldgate.
// 18 files bulk-uploaded into "07 · New uploads" in the SANDBOX (unpublished); the agent proposes
// filing them within the sandbox structure, creating folders where nothing fits, and holding
// ambiguous files for Tom's call. Publishing to bidders is a separate, later step.
// Grounded in telemetry: restructuring is Stifel's #2 feature; bulk filing is the operator's job.
import type { ChangeProposal, TreeNode } from './types';

export const FILING_COPY = {
  userPrompt:
    'I’ve just uploaded a batch of files to the staging area — file them into the sandbox structure, and propose new folders where nothing fits. Nothing moves until I approve.',
  formingMessage:
    'Reading the 18 files you just uploaded, then matching each one against the Project Aldgate sandbox structure before proposing anything.',
  proposalTitle: 'Filing plan ready',
  proposalSummary:
    'I matched your 18 uploads against the sandbox: 12 file straight into existing folders, 2 need new folders that the sandbox is missing, and I spotted 2 naming-convention breaks while I was in there. 4 files are held for your call — nothing moves until you approve.',
  reviewCta: 'Open filing plan',
  reviewInProgressCta: 'Filing plan open',
  reviewAppliedCta: 'Filed',
  updateCta: 'Apply filing plan',
  confirmationTitle: 'Apply filing plan?',
  confirmationBody:
    'This will move the approved uploads into place in the sandbox, create the two new folders, and apply the renames. Held-back files stay in staging. Everything stays unpublished — nothing becomes visible to bidders until you publish and approve the permission wave.',
  savedTitle: 'Filing plan applied',
  savedBody:
    'Filed in the sandbox. It picked up two new folders, and the audit trail is the same one manual filing leaves. Everything remains unpublished — the four held-back files are still in staging with notes attached.',
} as const;

export const FILING_HIGHLIGHTS = [
  'Cap table and customer contracts flagged sensitive — proposed Restricted, no bidder visibility until wave 2.',
  'Financial Model v8 looks like a new version of v7 already in the sandbox — held for your call.',
  'Two files are unreadable (password-protected, low-quality scan) — held back with a chase note.',
] as const;

export const FILING_RATIONALE =
  'Each upload was matched against the live sandbox structure by content, not filename. Where several files clustered with no home, I proposed a folder rather than forcing a bad fit. Anything ambiguous, sensitive, or version-conflicting is held for a human call — the agent files, the banker decides.';

export const filingSteps = [
  { id: 'read-uploads', label: 'Reading the 18 files you just uploaded', service: 'Documents' },
  { id: 'match-index', label: 'Matching each file against the Project Aldgate sandbox', service: 'Filing agent' },
  { id: 'duplicates', label: 'Detecting duplicates and prior versions', service: 'Filing agent' },
  { id: 'new-folders', label: 'Drafting new folders where the sandbox has no home', service: 'Filing agent' },
  { id: 'assemble', label: 'Assembling the filing plan for your review', service: 'Datasite AI' },
] as const;

export const filingSaveSteps = [
  { id: 'apply-moves', label: 'Filing approved uploads into the sandbox', service: 'Documents' },
  { id: 'create-folders', label: 'Creating the two approved folders', service: 'Documents' },
  { id: 'hold-back', label: 'Keeping held files in staging with notes', service: 'Filing agent' },
  { id: 'verify', label: 'Verifying audit trail', service: 'Activity log' },
] as const;

const filingNodes: TreeNode[] = [
  {
    id: 'a-finance',
    name: '03 Financials',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'a-fin-model-v7', name: '03.02.04 Financial Model v7 (Jun-2026).xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'a-fin-audited', name: '03.01.01 Audited Accounts FY2025.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'a-fin-mgmt', name: '03.03.01 Management Accounts Q2-2026 FINAL(2).xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
    ],
  },
  {
    id: 'a-commercial',
    name: '04 Commercial',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'a-comm-top50', name: '04.01.01 Top 50 Customers.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'a-comm-pipeline', name: '04.02.01 Pipeline Summary.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
    ],
  },
  {
    id: 'a-legal',
    name: '05 Legal',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'a-legal-articles', name: '05.01.01 Articles of Association.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'a-legal-shareholders', name: 'Shareholders Agreement - EXECUTED copy.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
  {
    id: 'a-tech',
    name: '06 Technology',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'a-tech-arch', name: '06.01.01 Platform Architecture Overview.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'a-tech-soc2', name: '06.03.01 SOC 2 Type II Report.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
  {
    id: 'a-uploads',
    name: '07 New uploads',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'u-arr-bridge', name: 'ARR bridge FY24-26 v3.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-cohort-smb', name: 'cohort_retention_SMB.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-cohort-ent', name: 'cohort_retention_ENTERPRISE(1).xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-churn-monthly', name: 'monthly churn by segment DRAFT.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-oss-register', name: 'open_source_register_export.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-oss-memo', name: 'OSS legal memo (external counsel).docx', kind: 'file', publishState: 'not-published', fileExt: 'docx' },
      { id: 'u-pen-test', name: 'Pen Test Executive Summary 2026.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-dpa', name: 'DPA template + GDPR annex.docx', kind: 'file', publishState: 'not-published', fileExt: 'docx' },
      { id: 'u-top20-contracts', name: 'Customer contracts - top 20 DRAFT.docx', kind: 'file', publishState: 'not-published', fileExt: 'docx' },
      { id: 'u-renewals', name: 'renewals_2026_pipeline v2.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-board-minutes', name: 'Board minutes Mar-Jun 2026.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-ip-assign', name: 'IP assignment deeds (founders).pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-employment', name: 'Key employment contracts bundle.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-tax-comp', name: 'Corp tax computations FY25.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-model-v8', name: 'Aldgate_Fin_Model_v8_FINAL(2).xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-cap-table', name: 'Cap table (do not share).xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'u-scan', name: 'scan0001.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'u-locked-lease', name: 'Lease bundle PASSWORD PROTECTED.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
];

const filingProposals: ChangeProposal[] = [
  {
    id: 'f-add-cohorts',
    type: 'add-folder',
    name: '03.05 Cohort analyses',
    parentId: 'a-finance',
    parentPath: ['03 Financials'],
    description: 'Four uploads are cohort/churn analyses with no home in the sandbox',
  },
  {
    id: 'f-add-oss',
    type: 'add-folder',
    name: '06.04 Open source',
    parentId: 'a-tech',
    parentPath: ['06 Technology'],
    description: 'OSS register and legal memo need a Technology sub-folder',
  },
  {
    id: 'f-move-arr',
    type: 'move',
    nodeId: 'u-arr-bridge',
    nodeName: 'ARR bridge FY24-26 v3.xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-cohorts',
    toPath: ['03 Financials', '03.05 Cohort analyses'],
    reason: 'ARR analysis — belongs with cohort work',
    dependsOn: ['f-add-cohorts'],
  },
  {
    id: 'f-move-cohort-smb',
    type: 'move',
    nodeId: 'u-cohort-smb',
    nodeName: 'cohort_retention_SMB.xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-cohorts',
    toPath: ['03 Financials', '03.05 Cohort analyses'],
    reason: 'Cohort retention analysis',
    dependsOn: ['f-add-cohorts'],
  },
  {
    id: 'f-move-cohort-ent',
    type: 'move',
    nodeId: 'u-cohort-ent',
    nodeName: 'cohort_retention_ENTERPRISE(1).xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-cohorts',
    toPath: ['03 Financials', '03.05 Cohort analyses'],
    reason: 'Cohort retention analysis',
    dependsOn: ['f-add-cohorts'],
  },
  {
    id: 'f-move-churn',
    type: 'move',
    nodeId: 'u-churn-monthly',
    nodeName: 'monthly churn by segment DRAFT.xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-cohorts',
    toPath: ['03 Financials', '03.05 Cohort analyses'],
    reason: 'Churn analysis — cohort family',
    dependsOn: ['f-add-cohorts'],
  },
  {
    id: 'f-move-oss-register',
    type: 'move',
    nodeId: 'u-oss-register',
    nodeName: 'open_source_register_export.xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-oss',
    toPath: ['06 Technology', '06.04 Open source'],
    reason: 'OSS register — new Technology sub-folder',
    dependsOn: ['f-add-oss'],
  },
  {
    id: 'f-move-oss-memo',
    type: 'move',
    nodeId: 'u-oss-memo',
    nodeName: 'OSS legal memo (external counsel).docx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'sug-f-add-oss',
    toPath: ['06 Technology', '06.04 Open source'],
    reason: 'Pairs with the OSS register',
    dependsOn: ['f-add-oss'],
  },
  {
    id: 'f-move-pentest',
    type: 'move',
    nodeId: 'u-pen-test',
    nodeName: 'Pen Test Executive Summary 2026.pdf',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-tech',
    toPath: ['06 Technology'],
    reason: 'Security document — sits beside SOC 2',
  },
  {
    id: 'f-move-dpa',
    type: 'move',
    nodeId: 'u-dpa',
    nodeName: 'DPA template + GDPR annex.docx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-legal',
    toPath: ['05 Legal'],
    reason: 'Data-privacy document — Legal',
  },
  {
    id: 'f-move-contracts',
    type: 'move',
    nodeId: 'u-top20-contracts',
    nodeName: 'Customer contracts - top 20 DRAFT.docx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-commercial',
    toPath: ['04 Commercial'],
    reason: 'Customer contracts — Commercial. Flagged sensitive: propose Restricted',
  },
  {
    id: 'f-move-renewals',
    type: 'move',
    nodeId: 'u-renewals',
    nodeName: 'renewals_2026_pipeline v2.xlsx',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-commercial',
    toPath: ['04 Commercial'],
    reason: 'Pipeline material — sits beside Pipeline Summary',
  },
  {
    id: 'f-move-board',
    type: 'move',
    nodeId: 'u-board-minutes',
    nodeName: 'Board minutes Mar-Jun 2026.pdf',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-legal',
    toPath: ['05 Legal'],
    reason: 'Corporate governance — Legal',
  },
  {
    id: 'f-move-ip',
    type: 'move',
    nodeId: 'u-ip-assign',
    nodeName: 'IP assignment deeds (founders).pdf',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-legal',
    toPath: ['05 Legal'],
    reason: 'IP documentation — Legal',
  },
  {
    id: 'f-move-employment',
    type: 'move',
    nodeId: 'u-employment',
    nodeName: 'Key employment contracts bundle.pdf',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-legal',
    toPath: ['05 Legal'],
    reason: 'Employment contracts — Legal',
  },
  {
    id: 'f-move-tax',
    type: 'move',
    nodeId: 'u-tax-comp',
    nodeName: 'Corp tax computations FY25.pdf',
    nodeKind: 'file',
    fromParentId: 'a-uploads',
    fromPath: ['07 New uploads'],
    toParentId: 'a-finance',
    toPath: ['03 Financials'],
    reason: 'Tax computation — Financials',
  },
  {
    id: 'f-rename-mgmt',
    type: 'rename',
    nodeId: 'a-fin-model-v7',
    oldName: '03.02.04 Financial Model v7 (Jun-2026).xlsx',
    newName: '03.02.04 Financial Model v7 (Jun-2026) — superseded by v8.xlsx',
    nodeKind: 'file',
    parentPath: ['03 Financials'],
    reason: 'Mark the prior model version pending your call on v8',
  },
  {
    id: 'f-rename-shareholders',
    type: 'rename',
    nodeId: 'a-legal-shareholders',
    oldName: 'Shareholders Agreement - EXECUTED copy.pdf',
    newName: '05.02.01 Shareholders Agreement (executed).pdf',
    nodeKind: 'file',
    parentPath: ['05 Legal'],
    reason: 'Naming-convention break spotted while filing',
  },
];

// Held for Tom's call (no proposal generated — deliberately):
// u-model-v8 (version conflict), u-cap-table (sensitive), u-scan + u-locked-lease (unreadable).
export const filingScenario = {
  rootName: 'Project Aldgate',
  nodes: filingNodes,
  proposals: filingProposals,
} as const;
