import type { Scenario, ChangeProposal, TreeNode } from '../types';

const nodes: TreeNode[] = [
  {
    id: 'h-legal',
    name: 'Legal',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-legal-msa', name: 'MSA-2024.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-legal-nda', name: 'NDA-template.docx', kind: 'file', publishState: 'not-published', fileExt: 'docx' },
      { id: 'h-legal-incorp', name: 'Certificate of Incorporation.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-legal-bylaws', name: 'Bylaws v2.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-legal-shareholder', name: 'Shareholder Agreement.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-legal-litigation', name: 'Litigation Summary.docx', kind: 'file', publishState: 'not-published', fileExt: 'docx' },
    ],
  },
  {
    id: 'h-finance',
    name: 'Financials',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-finance-q1', name: 'Q1-summary.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-finance-q2', name: 'Q2 summary FINAL.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-finance-q3', name: 'Q3-summary.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-finance-fy23', name: 'FY2023 Audited Financials.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-finance-fy24', name: 'FY2024 Audited Financials.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-finance-budget', name: 'Budget Forecast 2025.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-finance-ap', name: 'Accounts Payable Aging.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
    ],
  },
  {
    id: 'h-diligence',
    name: 'Diligence',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-dil-checklist', name: 'Due Diligence Checklist.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-dil-mgmt', name: 'Management Presentation.pptx', kind: 'file', publishState: 'not-published', fileExt: 'pptx' },
      { id: 'h-dil-cim', name: 'CIM Final.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-dil-qa', name: 'Buyer Q&A Log.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
    ],
  },
  {
    id: 'h-commercial',
    name: 'Commercial',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-comm-customers', name: 'Top 25 Customers.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-comm-pipeline', name: 'Sales Pipeline Q4.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-comm-pricing', name: 'Pricing Strategy.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-comm-channel', name: 'Channel Partner Agreements.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-comm-marketing', name: 'Marketing Plan 2025.pptx', kind: 'file', publishState: 'not-published', fileExt: 'pptx' },
    ],
  },
  {
    id: 'h-tech',
    name: 'Technology',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-tech-arch', name: 'System Architecture.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-tech-roadmap', name: 'Product Roadmap 2025.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-tech-ip', name: 'IP Portfolio Summary.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-tech-security', name: 'Security & Compliance Audit.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
  {
    id: 'h-tax',
    name: 'Tax',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-tax-fy23', name: 'Federal Return FY2023.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-tax-fy24', name: 'Federal Return FY2024.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-tax-state', name: 'State Tax Filings.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
  {
    id: 'h-insurance',
    name: 'Insurance',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-ins-do', name: 'D&O Policy.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-ins-cyber', name: 'Cyber Liability Policy.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-ins-claims', name: 'Claims History.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
    ],
  },
  {
    id: 'h-misc',
    name: 'Misc',
    kind: 'folder',
    publishState: 'not-published',
    children: [
      { id: 'h-misc-org', name: 'Employee Org Charts.pptx', kind: 'file', publishState: 'not-published', fileExt: 'pptx' },
      { id: 'h-misc-team', name: 'Team Roster v3.xlsx', kind: 'file', publishState: 'not-published', fileExt: 'xlsx' },
      { id: 'h-misc-handbook', name: 'Employee Handbook.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
      { id: 'h-misc-benefits', name: 'Benefits Summary 2025.pdf', kind: 'file', publishState: 'not-published', fileExt: 'pdf' },
    ],
  },
  { id: 'h-empty-1', name: 'Old Drafts', kind: 'folder', publishState: 'not-published', children: [] },
  { id: 'h-empty-2', name: 'Archive 2022', kind: 'folder', publishState: 'not-published', children: [] },
];

const proposals: ChangeProposal[] = [
  {
    id: 'p-add-1',
    type: 'add-folder',
    name: 'Contracts',
    parentId: 'h-legal',
    parentPath: ['Legal'],
    description: 'Group contract documents under Legal',
  },
  {
    id: 'p-add-2',
    type: 'add-folder',
    name: 'Human Resources',
    parentId: '__root__',
    parentPath: [],
    description: 'Top-level HR section for org and roster files',
  },
  {
    id: 'p-move-1',
    type: 'move',
    nodeId: 'h-misc-org',
    nodeName: 'Employee Org Charts.pptx',
    nodeKind: 'file',
    fromParentId: 'h-misc',
    fromPath: ['Misc'],
    toParentId: 'sug-p-add-2',
    toPath: ['Human Resources'],
    reason: 'HR document — belongs under Human Resources',
    dependsOn: ['p-add-2'],
  },
  {
    id: 'p-move-2',
    type: 'move',
    nodeId: 'h-misc-team',
    nodeName: 'Team Roster v3.xlsx',
    nodeKind: 'file',
    fromParentId: 'h-misc',
    fromPath: ['Misc'],
    toParentId: 'sug-p-add-2',
    toPath: ['Human Resources'],
    reason: 'HR document — belongs under Human Resources',
    dependsOn: ['p-add-2'],
  },
  {
    id: 'p-rename-1',
    type: 'rename',
    nodeId: 'h-finance-q2',
    oldName: 'Q2 summary FINAL.xlsx',
    newName: 'Q2-summary.xlsx',
    nodeKind: 'file',
    parentPath: ['Financials'],
    reason: 'Match naming convention of Q1-summary.xlsx',
  },
  {
    id: 'p-add-3',
    type: 'add-folder',
    name: 'Audited Financials',
    parentId: 'h-finance',
    parentPath: ['Financials'],
    description: 'Group audited financial statements',
  },
  {
    id: 'p-move-3',
    type: 'move',
    nodeId: 'h-finance-fy23',
    nodeName: 'FY2023 Audited Financials.pdf',
    nodeKind: 'file',
    fromParentId: 'h-finance',
    fromPath: ['Financials'],
    toParentId: 'sug-p-add-3',
    toPath: ['Financials', 'Audited Financials'],
    reason: 'Group under Audited Financials',
    dependsOn: ['p-add-3'],
  },
  {
    id: 'p-rename-2',
    type: 'rename',
    nodeId: 'h-misc',
    oldName: 'Misc',
    newName: 'Reference',
    nodeKind: 'folder',
    parentPath: [],
    reason: 'More descriptive name',
  },
];

export const happy: Scenario = {
  id: 'happy',
  label: 'Sandbox happy path',
  rootName: 'Project Atlas',
  nodes,
  proposals,
  prompt: 'Reorganize the file room into clear top-level sections with consistent naming.',
  attachmentChip: '8 changes',
};
